# Site wide configuration

title:       Joe Davis
blog-name:   Joe Davis' blog
locale:      en_US
# url for local debugging
#url:        http://localhost:4000
# url for live website
url:         http://joedavisdev.co.uk
description:


# Jekyll configuration
permalink:   posts/:year/:month/:day/:title
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  input: GFM

# Site owner
owner:
  name: Joe Davis
  avatar: bio-photo.jpg
  bio: "3D graphics enthusiast & ocassional app developer. Game Ecosystem Developer Relations Engineer, Samsung Electronics. Previously developer support lead for PowerVR Graphics."
  email: joedavisdev@gmail.com
  disqus-shortname: joedavisdev
  twitter: joedavisdev
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: joedavisdev
  stackoverflow: 860284/joe-davis
  linkedin: joedavisdev
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  img-blog: joedavis
  img-forum: joe-2

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
